 **1)Get two positive integers start and end from the user and write a Python program to print all Prime numbers in that Interval.**

In [ ]:
s={"aman", "222", 777, 400.4}
print(s)

{400.4, 777, '222', 'aman'}


2)**Create** a dictionary of your basic data: (a) Roll No (b) Last Name (c) First Name (d) Date of birth. Print out the values and keys. ***

In [ ]:
s={"roll no" : "cse20228",
    "firstname": "Karthik",
    "lastname": "srikakolapu",
    "dob": "21-06-2003"}
print(s)

{'roll no': 'cse20228', 'firstname': 'Karthik', 'lastname': 'srikakolapu', 'dob': '21-06-2003'}


3)Use rand function to generate a 2-dimensional random array with seed. 

In [ ]:
import numpy as np
from numpy import random
np.random.seed(5)
x=random.randint(20,size=(2,3))
print(x)


[[ 3 14 15]
 [ 6 16  9]]


4)Generate a single random number in [0.0, 1.0]. Find the absolute value of (-1234) 

In [ ]:
import random
print(random.uniform(0.0, 1.0))


0.5171785568557263


5)Return a random integer N such that 20 <= N <= 90.  

In [ ]:
t = random.randint(20,90)
print(t)

58


6)Given a population or set[11, 12, 13,14, 15] 

Return a 3 length list of unique elements without replacement. 

Shuffle the above set 

Print a random number from the set 

In [ ]:
pop = [11,12,13,14,15]
np.random.shuffle(pop)
print(pop)
print(pop[random.randint(0,5)])
temp=[pop.pop(random.randint(0,5)),pop.pop(random.randint(0,4)),pop.pop(random.randint(0,3))]
print(temp)

[12, 15, 13, 11, 14]
15
[15, 11, 14]


7)Write the text "The King is Dead, Long Live The King" on to a file in your hard drive; read and print the text.

In [ ]:
f = open('test.txt','w')
f.write('The King is Dead, Long Live The King')
f.close()
f = open('test.txt','r')
for i in f:
  print(i,end=" ")
f.close()

The King is Dead, Long Live The King 

9)Given a string "The King is Dead, Long Live The King"  

Print the complete string 

Print first character of the string 

Print characters starting from 3rd to 5th 

Print string starting from 3rd character 

Split the words 

In [ ]:
dd="The King is Dead, Long Live The King"
print(dd)

The King is Dead, Long Live The King


In [ ]:
print(dd[0:1])
print(dd[2:5])
print(dd[2:])

T
e K
e King is Dead, Long Live The King


10)Arrays can be multidimensional. Create a two-dimensional array of (1,2,3) and (4,5,6). 

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


11)Array slicing works with multiple dimensions in the same way as usual, applying each slice specification as a filter to a specified dimension. Consider two-dimensional array of (1,2,3) and (4,5,6). 

Slice and display the 2nd row. 

Write code to display as array([2., 5.])  

Find the length of the array.

In [ ]:
print(arr[1])
print(len(arr))

[4 5 6]
2


12)Arrays can be reshaped using tuples that specify new dimensions. Turn a ten-element one-dimensional array into a two-dimensional one whose first axis has five elements and whose second axis has two elements. Obtain the transpose of the array 

In [ ]:
ar=np.array([1,2,3,4,5,6,7,8,9,0])
print(ar)
ar=ar.reshape(2,5)
print(ar)

[1 2 3 4 5 6 7 8 9 0]
[[1 2 3 4 5]
 [6 7 8 9 0]]


13)Create an array from a list of 1,2 and 3. 

In [ ]:
import numpy as np
my_list = [1,2,3]
arr= np.array(my_list)
print(arr)


[1 2 3]


14)Fill an array [1,2,3] with a single value [9,9,9].  

In [ ]:
a15=[1,2,3]
a15=np.full((3),9)
print(a15)

[9 9 9]


15)Sum the elements of array [2,4,5]. 

In [ ]:
a16=[2,4,5]
print(sum(a16))

16)Give the products of array [77,74,75] 

In [ ]:
a17=[77,74,75]
prod=1
for i in a17:
  prod*=i
print(prod)

427350


17)Given an array [2,1,9,1,2,22,1,1,4,55,6,2,56]. Find mean, variance, max, min, argmin, median, argmax and standard deviation. 

In [ ]:
import numpy as np

In [ ]:
from scipy import stats
ttt=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print("Mean=",np.mean(ttt))
print("Median=",np.median(ttt))
print("Mode=",stats.mode(ttt))
print("Max=",max(ttt))
print("Min=",min(ttt))

Mean= 12.461538461538462
Median= 2.0
Mode= ModeResult(mode=array([1]), count=array([4]))
Max= 56
Min= 1


18)Extract unique elements from an array: [1, 1, 4, 5, 5, 5, 7] and sort it. 



In [ ]:
a19=[1, 1, 4, 5, 5, 5, 7]
a19=list(set(a19))
a19.sort()
print(a19)

[1, 4, 5, 7]


19)Find dot product of two arrays [1, 2, 3]and [0, 1, 1].  



In [ ]:
a20=[1,2,3]
b20=[0,1,1]
print(np.dot(a20,b20))

5


20)Find the eigenvalues and eigenvectors of matrix A. 

In [ ]:
a21=[[2,-12],[1,-5]]
x,y=np.linalg.eig(a21)
print(x,y)

[-1. -2.] [[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]
